### ISSUE TITLE
Test the "Load more" and "Back to top" buttons at the bottom of Teach page

### ISSUE THREAD

**Issue by bitgeeky** [mozilla/webmaker-tests#36]
Steps:
1 Go to Home Page 
2 Click on the Make tab (next to Explore)
3 Scroll to the bottom of Page
4 Check if "Load More" and "Back to top" buttons are visible.
5 Click on Load More button and Assert that: Number of displayed results have increased
6 Click on Back to top and assert that the Header bar is visible

**Comment by davehunt** [comment]
We're not currently maintaining this repository.
