### ISSUE TITLE
Verify that account creation on the home page works

### ISSUE THREAD

**Issue by jbuck** [mozilla/webmaker-tests#43]
On the homepage of webmaker.org, we have 3 buttons that all trigger the sign-up/sign-in flow. "Sign in" on the top, "Create an account" and "Signin" in the "We teach the web" area.

Clicking any of these 3 buttons will trigger a Persona sign-up. Once that has succeeded, a modal will pop-up asking for a username.

I'm not sure of the best way to do this on production, but on staging you can create as many users as you like!

**Comment by davehunt** [comment]
We're not currently maintaining this repository.
