### ISSUE TITLE
Verify that account sign-in on the home page works

### ISSUE THREAD

**Issue by jbuck** [mozilla/webmaker-tests#44]
On the homepage of webmaker.org, we have 3 buttons that all trigger the sign-up/sign-in flow. "Sign in" on the top, "Create an account" and "Signin" in the "We teach the web" area.

Clicking any of these 3 buttons will trigger a Persona sign-up. Once that has succeeded, you should be signed in (verify with the username on the top right corner?)

We could make a WebQAAutomation user on staging and production to verify that the account sign-in works.

**Comment by davehunt** [comment]
We're not currently maintaining this repository.
